= Примеры для создания systemd сервиса для управления docker-compose
:tip-caption: 💡

В этом проекте собраны примеры файлов для создания сервиса из docker-compose сборки.

== Файлы

[cols=2*,options="header"]
|===
| Файл | Назначение
| `/[working_dir]/docker-compose.yml` | Compose файл описывает, что разворачивать
| `/etc/systemd/system/app_name.service` | Описание сервиса для упраления docker-compose приложением
| `/etc/systemd/system/app_name-reload.service` | Исполняемая инструкция для перезагрузки сервиса описанного в `[app_name].service`
| `/etc/systemd/system/app_name-reload.timer` | Таймер для планирования перезагрузок
|===

== Установка

Переименуйте соответсвующие файлы и поместите их в нужные директории, после чего отредактируйте согласно текущей инсталяци.
Затем нужно перезагрузить systemd:

WARNING: В файле `app_name.service` обязательно поменяйте `[working_dir]` на папку,
в которой находится ваше приложение и файл `docker-compose.yml`. Также в поле `description`
напишите название вашего приложения

CAUTION: поменяйте во всех файлах `[app_name]` на имя вашего приложения (сервиса)

```bash
# systemctl daemon-reload
# systemctl enable [app_name] [app_name]-reload
# systemctl start [app_name] [app_name]-reload
```

TIP: в приципе обязательным является только один файл `app_name.service`, остальные
обеспечивают регулярный перезапуск
